### ISSUE TITLE
STM32 f4 MCU core

### ISSUE THREAD

**Issue by DprasK** [Ant2000/CustomJWT#5]
Hello, i want to use CustomJWT on STM32. If i used it on maple core, customjwt can work properly. But i must run it on mcu core and i get this error

In file included from C:\Users\beacon_engineering\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h:132,
                 from C:\Users\beacon_engineering\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\cores\arduino/stm32/stm32_def.h:36,
                 from C:\Users\beacon_engineering\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\cores\arduino/stm32/clock.h:19,
                 from C:\Users\beacon_engineering\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\cores\arduino/wiring_time.h:23,
                 from C:\Users\beacon_engineering\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\cores\arduino/wiring.h:38,
                 from C:\Users\beacon_engineering\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\cores\arduino/Arduino.h:36,
                 from c:\Users\beacon_engineering\Documents\Arduino\libraries\Crypto\src\RNG.cpp:27:
C:\Users\beacon_engineering\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f407xx.h:1134:43: error: expected ')' before '*' token
 1134 | #define RNG                 ((RNG_TypeDef *) RNG_BASE)
      |                              ~            ^
c:\Users\beacon_engineering\Documents\Arduino\libraries\Crypto\src\RNG.cpp:159:10: note: in expansion of macro 'RNG'
  159 | RNGClass RNG;
      |          ^~~
C:\Users\beacon_engineering\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f407xx.h:1134:43: error: expected ')' before '*' token
 1134 | #define RNG                 ((RNG_TypeDef *) RNG_BASE)
      |                             ~             ^
c:\Users\beacon_engineering\Documents\Arduino\libraries\Crypto\src\RNG.cpp:159:10: note: in expansion of macro 'RNG'
  159 | RNGClass RNG;
      |          ^~~

exit status 1

Compilation error: exit status 1

**Comment by Ant2000** [comment]
Hello,
I looked into the issue. It seems to be caused by a externed variable called RNG in the Crypto library conflicting with a macro called RNG in the STM32 HW libraries.
To fix it, you can either:
1) Add the line #undef RNG on top of the RNG.h file present in the Crypto library source files
2) Download the latest version of the library (v2.1.1) that has removed Crypto as a dependency
